//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Chess.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black is check..
        /// </summary>
        internal static string BLACK_CHECK {
            get {
                return ResourceManager.GetString("BLACK_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black is mate..
        /// </summary>
        internal static string BLACK_MATE {
            get {
                return ResourceManager.GetString("BLACK_MATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black is out of time..
        /// </summary>
        internal static string BLACK_TIME {
            get {
                return ResourceManager.GetString("BLACK_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black victory!.
        /// </summary>
        internal static string BLACK_WIN {
            get {
                return ResourceManager.GetString("BLACK_WIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check!.
        /// </summary>
        internal static string CHECK {
            get {
                return ResourceManager.GetString("CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw!.
        /// </summary>
        internal static string DRAW {
            get {
                return ResourceManager.GetString("DRAW", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap EngineMove {
            get {
                object obj = ResourceManager.GetObject("EngineMove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifty move draw..
        /// </summary>
        internal static string FIFTY_MOVE_RULE {
            get {
                return ResourceManager.GetString("FIFTY_MOVE_RULE", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap FlipView {
            get {
                object obj = ResourceManager.GetObject("FlipView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient pieces..
        /// </summary>
        internal static string INSUFFICIENT_PIECES {
            get {
                return ResourceManager.GetString("INSUFFICIENT_PIECES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move repetition..
        /// </summary>
        internal static string MOVE_REPETITION {
            get {
                return ResourceManager.GetString("MOVE_REPETITION", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap NewGame {
            get {
                object obj = ResourceManager.GetObject("NewGame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NextGame {
            get {
                object obj = ResourceManager.GetObject("NextGame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NextMove {
            get {
                object obj = ResourceManager.GetObject("NextMove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrevGame {
            get {
                object obj = ResourceManager.GetObject("PrevGame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PrevMove {
            get {
                object obj = ResourceManager.GetObject("PrevMove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stalemate..
        /// </summary>
        internal static string STALEMATE {
            get {
                return ResourceManager.GetString("STALEMATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White is check..
        /// </summary>
        internal static string WHITE_CHECK {
            get {
                return ResourceManager.GetString("WHITE_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White is mate..
        /// </summary>
        internal static string WHITE_MATE {
            get {
                return ResourceManager.GetString("WHITE_MATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White is out of time..
        /// </summary>
        internal static string WHITE_TIME {
            get {
                return ResourceManager.GetString("WHITE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White victory!.
        /// </summary>
        internal static string WHITE_WIN {
            get {
                return ResourceManager.GetString("WHITE_WIN", resourceCulture);
            }
        }
    }
}
